name: 'pr-commit-msg-linting'
description: 'pr commit message linting github action'
author: 'Ashu Rana'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  title-regex:
    description: 'Title regex to match'
    required: true
